# Generated by Django 3.0.6 on 2020-07-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_auto_20200710_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
