# Generated by Django 3.0.6 on 2020-07-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0010_auto_20200710_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
